### ISSUE TITLE
Horizon on MAC big sur doesn't work

### ISSUE THREAD

**Issue by girishkumarbk** [open-horizon/open-horizon.github.io#55] opened 2021-02-24 14:30 UTC
root# curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
----------- Verifying input and the host OS...
Management hub services will listen on 127.0.0.1
Installing prerequisites using brew, this could take a minute...
Error running brew install jq gettext: Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

MacOS: Big Sur 11.0.1

**Comment by joewxboy** [comment] 2021-03-01 00:18
@bmpotter Should I move this issue to the `devops` repo?

**Comment by girishkumarbk** [comment] 2021-03-01 07:09
Sure. Thx

**Comment by bmpotter** [comment] 2021-03-01 15:34
@girishkumarbk can you reopen this issue in https://github.com/open-horizon/devops/issues ? Thx

**Comment by bmpotter** [comment] 2021-04-16 14:32
This issue is now a duplicate of https://github.com/open-horizon/devops/issues/48 , so i'm closing this one.

**Closed by bmpotter** 2021-04-16 14:32 UTC
